### ISSUE TITLE
Create lab

### ISSUE THREAD

**Issue by arthurdm** [microservices-api/appsody-okd-lab#1]
We should create a lab, similar to https://github.com/microservices-api/kubernetes-microprofile-lab, which showcases appsody - highlighting the operator.

Suggested set of steps:

- [x] Quickly walkthrough the [template](https://github.com/appsody/stacks/tree/master/incubator/java-microprofile/image) that an enterprise architect (Champ) would curate.  Special focus to the Dockerfiles used to build the dev image and prod image.  This is where Champ can configure the enterprise image.

- [x] Now switching into the developer persona (Jane), use `appsody list` and `appsody init` to create a new Java MicroProfile project.

- [x] Open project with VS Code and walk through health endpoints we got from the template

- [x] Copy / paste fully developed resource (1 Java file), which has basic create / update / delete JAXRS methods.  
    *  This Java file should use some basic MP OpenAPI annotations (could be just method descriptions), and should have 1 MP Config variable so that we can showcase how we can pass an environment variable through the Operator.  The MP Config var could be simply passing the name of the person and having a `/hello` resource that said `Hello + <name>`.  

- [x] Execute `appsody build` to build the image

- [x] Execute `appsody run` (need to specify env var) to show how we can debug it locally it first

- [x] Execute `appsody deploy --generate-only` to generate the base YAML file.  Can edit to include the env var we need, and turn on expose=true.  

- [x] Execute `appsody deploy` to deploy the app, and then show it on OKD's UI.  Show the route and the MP OpenAPI UI.  

- [x] Make an update to the Java file and create a new `v2` tag of the image

- [x] Deploy the new tagged app using `appsody deploy` (expose=true) 

- [x] Change the route to do a 80/20 deployment (v1/v2) to mimic A/B testing

- [x] Do a few curl commands to a resource that was changed (this is to show the output difference between v1 and v2).  

- [x] Once satisfied, change the route to be 100% for v2.  Delete the first `appsodyapplication`.

- [x] Bonus part:   edit the v2 YAML to have persistence for `/logs` and demonstrate how this change takes effect.  Look at the persisted logs.

**Comment by leochr** [comment]
Added lab instructions.
